# Generated by Django 6.0.1 on 2026-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BruteForceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('attempts', models.IntegerField()),
                ('severity', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('logon_type', models.CharField(max_length=50)),
            ],
        ),
    ]
